name: quran_for_blind_app_flutter
description: Noble Quran app for Visually Challenged, with word by word meaning

publish_to: 'none'

version: 1.0.0+3

environment:
  sdk: '>=2.18.0-189.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  noble_quran:
    git: https://github.com/hashirabdulbasheer/noble_quran_flutter_package
  url_launcher: ^6.1.10


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Alvi
      fonts:
        - asset: assets/fonts/AlMushafQuran.ttf
